# Generated by Django 4.2.16 on 2024-11-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_data',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
