# Generated by Django 4.2.16 on 2024-11-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0003_caste_fatherprofile_hobby_religion_sect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sects', to='matrimony.sect'),
        ),
    ]
