# Generated by Django 4.2.16 on 2024-11-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0004_alter_profile_religion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'Hobby', 'verbose_name_plural': 'Hobbies'},
        ),
        migrations.AddField(
            model_name='profile',
            name='sect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sects', to='matrimony.sect'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='matrimony.religion'),
        ),
    ]
