# Generated by Django 4.2.16 on 2024-11-12 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0005_alter_hobby_options_profile_sect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='matrimony.sect'),
        ),
    ]
