# Generated by Django 4.2.16 on 2024-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0006_alter_profile_sect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='matrimony.hobby'),
        ),
    ]
